name: Java CI

on:
  push:
    branches:
      - 'master'
      - 'feature/**'
    paths:
      - '**.gradle*'
      - '**.properties'
      - '**/src/**'
      - '.github/workflows/**'
    tags-ignore:
      - '*.*'
  pull_request:
    paths:
      - '**.gradle*'
      - '**.properties'
      - '**/src/**'
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build for JVM ${{ matrix.java }}
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name != 'Masterzach32/facet' }}
    strategy:
      matrix:
        java: [ 8, 11, 16 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build Project
        run: ./gradlew build
  publish:
    name: Publish artifacts
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Publish
        run: ./gradlew -x test publish
        env:
          ORG_GRADLE_PROJECT_maven_username: ${{ secrets.maven_username }}
          ORG_GRADLE_PROJECT_maven_password: ${{ secrets.maven_password }}
